import React, { useState, useEffect } from 'react';
import { Plus, UserCircle2, ExternalLink, Trash2, Edit, Layout, Search } from 'lucide-react';
import { BioProfile, LinkData } from '../types';
import { supabaseAdapter } from '../services/storage/supabaseAdapter';
import { toast } from 'sonner';
import { useAuth } from '../contexts/AuthContext';
import { v4 as uuidv4 } from 'uuid';
import BioPreview from '../components/BioPreview';
import BioAppearanceEditor from '../components/BioAppearanceEditor';
import { SortableBioLinkItem } from '../components/SortableBioLinkItem';
import {
    DndContext,
    closestCenter,
    KeyboardSensor,
    PointerSensor,
    useSensor,
    useSensors,
    DragEndEvent
} from '@dnd-kit/core';
import {
    arrayMove,
    SortableContext,
    sortableKeyboardCoordinates,
    verticalListSortingStrategy,
} from '@dnd-kit/sortable';

const BioDashboard: React.FC = () => {
    const { user } = useAuth();
    const [profiles, setProfiles] = useState<BioProfile[]>([]);
    const [isEditing, setIsEditing] = useState(false);
    const [currentProfile, setCurrentProfile] = useState<Partial<BioProfile>>({});
    const [activeTab, setActiveTab] = useState<'details' | 'appearance'>('details');
    const [availableLinks, setAvailableLinks] = useState<LinkData[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchQuery, setSearchQuery] = useState('');

    useEffect(() => {
        if (user) {
            fetchData();
        }
    }, [user]);

    const fetchData = async () => {
        try {
            setLoading(true);
            if (!user) return;
            const [fetchedProfiles, fetchedLinks] = await Promise.all([
                supabaseAdapter.getBioProfiles(user.id),
                supabaseAdapter.getLinks()
            ]);
            setProfiles(fetchedProfiles);
            setAvailableLinks(fetchedLinks);
        } catch (error) {
            console.error('Error fetching bio data:', error);
        } finally {
            setLoading(false);
        }
    };

    const sensors = useSensors(
        useSensor(PointerSensor),
        useSensor(KeyboardSensor, {
            coordinateGetter: sortableKeyboardCoordinates,
        })
    );

    const handleDragEnd = (event: DragEndEvent) => {
        const { active, over } = event;

        if (active.id !== over?.id) {
            const currentLinks = currentProfile.links || [];
            const oldIndex = currentLinks.indexOf(active.id as string);
            const newIndex = currentLinks.indexOf(over?.id as string);

            if (oldIndex !== -1 && newIndex !== -1) {
                const newLinks = arrayMove(currentLinks, oldIndex, newIndex);
                setCurrentProfile({ ...currentProfile, links: newLinks });
            }
        }
    };

    const handleCreateNew = () => {
        setCurrentProfile({
            id: uuidv4(),
            handle: '',
            displayName: user?.displayName || '',
            bio: '',
            avatarUrl: user?.avatar_url || '',
            theme: 'dark',
            links: [],
            views: 0
        });
        setActiveTab('details');
        setIsEditing(true);
    };

    const handleEdit = (profile: BioProfile) => {
        setCurrentProfile({ ...profile });
        setActiveTab('details');
        setIsEditing(true);
    };

    const handleSave = async () => {
        console.log('handleSave called', currentProfile);
        if (!currentProfile.handle || !currentProfile.displayName) {
            toast.error('Please fill in the Handle and Display Name fields.');
            return;
        }

        try {
            // Check if we are updating an existing profile
            const isUpdating = profiles.some(p => p.id === currentProfile.id);
            console.log('isUpdating:', isUpdating, 'id:', currentProfile.id);

            if (isUpdating && currentProfile.id) {
                await supabaseAdapter.updateBioProfile(currentProfile.id, {
                    ...currentProfile,
                    links: currentProfile.links || []
                });
            } else {
                // Creating new profile
                // Remove ID if it was auto-generated by uuidv4() in handleCreateNew
                // The adapter/DB will generate a real ID
                const { id, views, ...newProfileData } = currentProfile as BioProfile;
                console.log('Creating profile with data:', newProfileData);
                await supabaseAdapter.createBioProfile({
                    ...newProfileData,
                    links: currentProfile.links || []
                });
            }

            fetchData();
            setIsEditing(false);
        } catch (error: any) {
            console.error('Error saving profile:', error);
            if (error.message?.includes('duplicate key value violates unique constraint')) {
                toast.error('This handle is already taken. Please choose another one.');
            } else {
                toast.error(`Failed to save profile: ${error.message || 'Unknown error'}`);
            }
        }
    };

    const handleDelete = async (id: string) => {
        if (confirm('Delete this bio profile?')) {
            try {
                await supabaseAdapter.deleteBioProfile(id);
                fetchData();
            } catch (error) {
                console.error('Error deleting profile:', error);
                toast.error('Failed to delete profile.');
            }
        }
    };

    const toggleLinkSelection = (linkId: string) => {
        const currentLinks = currentProfile.links || [];
        if (currentLinks.includes(linkId)) {
            setCurrentProfile({ ...currentProfile, links: currentLinks.filter(id => id !== linkId) });
        } else {
            setCurrentProfile({ ...currentProfile, links: [...currentLinks, linkId] });
        }
    };

    const activeLinksList = (currentProfile.links || [])
        .map(id => availableLinks.find(l => l.id === id))
        .filter((l): l is LinkData => !!l);

    const inactiveLinksList = availableLinks.filter(l => !(currentProfile.links || []).includes(l.id));

    const filteredProfiles = profiles.filter(profile =>
        profile.displayName.toLowerCase().includes(searchQuery.toLowerCase()) ||
        profile.handle.toLowerCase().includes(searchQuery.toLowerCase())
    );

    if (isEditing) {
        return (
            <div className="p-8 max-w-4xl mx-auto">
                <h2 className="text-2xl font-bold text-slate-900 mb-6">
                    {currentProfile.id ? 'Edit Profile' : 'Create Bio Profile'}
                </h2>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div className="space-y-4">
                        {/* Tabs */}
                        <div className="flex bg-stone-100 p-1 rounded-xl mb-4">
                            <button
                                onClick={() => setActiveTab('details')}
                                className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all ${activeTab === 'details' ? 'bg-white text-slate-900 shadow-sm' : 'text-stone-500 hover:text-slate-700'}`}
                            >
                                Details
                            </button>
                            <button
                                onClick={() => setActiveTab('appearance')}
                                className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all ${activeTab === 'appearance' ? 'bg-white text-slate-900 shadow-sm' : 'text-stone-500 hover:text-slate-700'}`}
                            >
                                Appearance
                            </button>
                        </div>

                        {/* Details Tab Content */}
                        <div className={`bg-white border border-stone-200 rounded-xl p-6 shadow-sm ${activeTab === 'details' ? 'block' : 'hidden'}`}>
                            <h3 className="text-slate-900 font-bold mb-4">Profile Details</h3>
                            <div className="space-y-3">
                                <div>
                                    <label className="text-xs text-stone-500 block mb-1">Handle (URL slug)</label>
                                    <div className="flex bg-stone-50 border border-stone-200 rounded-lg overflow-hidden">
                                        <span className="px-3 py-2 text-stone-400 text-sm bg-stone-100">links.trak.in/p/</span>
                                        <input
                                            type="text"
                                            value={currentProfile.handle}
                                            onChange={e => setCurrentProfile({ ...currentProfile, handle: e.target.value })}
                                            className="flex-1 bg-transparent border-none text-slate-900 focus:ring-0 p-2"
                                            placeholder="alex"
                                        />
                                    </div>
                                </div>
                                <div>
                                    <label className="text-xs text-stone-500 block mb-1">Display Name</label>
                                    <input
                                        type="text"
                                        value={currentProfile.displayName}
                                        onChange={e => setCurrentProfile({ ...currentProfile, displayName: e.target.value })}
                                        className="w-full bg-stone-50 border border-stone-200 rounded-lg p-2 text-slate-900"
                                        placeholder="Alex Chen"
                                    />
                                </div>
                                <div>
                                    <label className="text-xs text-stone-500 block mb-1">Bio</label>
                                    <textarea
                                        value={currentProfile.bio}
                                        onChange={e => setCurrentProfile({ ...currentProfile, bio: e.target.value })}
                                        className="w-full bg-stone-50 border border-stone-200 rounded-lg p-2 text-slate-900 h-20"
                                        placeholder="Tech enthusiast & content creator."
                                    />
                                </div>
                                <div>
                                    <label className="text-xs text-stone-500 block mb-1">Avatar URL</label>
                                    <input
                                        type="text"
                                        value={currentProfile.avatarUrl}
                                        onChange={e => setCurrentProfile({ ...currentProfile, avatarUrl: e.target.value })}
                                        className="w-full bg-stone-50 border border-stone-200 rounded-lg p-2 text-slate-900"
                                        placeholder="https://..."
                                    />
                                </div>
                                <div>
                                    <label className="text-xs text-stone-500 block mb-1">Theme</label>
                                    <select
                                        value={currentProfile.theme}
                                        onChange={e => setCurrentProfile({ ...currentProfile, theme: e.target.value as any })}
                                        className="w-full bg-stone-50 border border-stone-200 rounded-lg p-2 text-slate-900"
                                    >
                                        <option value="vibrant">Vibrant (Pop!)</option>
                                        <option value="glass">Glass (Modern Dark)</option>
                                        <option value="industrial">Industrial (Technical)</option>
                                        <option value="retro">Retro Pop (90s)</option>
                                        <option value="cyberpunk">Cyberpunk (Neon)</option>
                                        <option value="neubrutalism">Neubrutalism (Bold)</option>
                                        <option value="lofi">Lofi (Chill)</option>
                                        <option value="clay">Claymorphism (Soft 3D)</option>
                                        <option value="bauhaus">Bauhaus (Geometric)</option>
                                        <option value="lab">Lab (Scientific)</option>
                                        <option value="archive">Archive (Vintage)</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        {/* Appearance Tab Content */}
                        <div className={activeTab === 'appearance' ? 'block' : 'hidden'}>
                            {currentProfile.id && (
                                <BioAppearanceEditor
                                    profile={currentProfile as BioProfile}
                                    onChange={(updates) => setCurrentProfile(prev => ({ ...prev, ...updates }))}
                                />
                            )}
                        </div>
                    </div>

                    <div className="space-y-4">
                        <div className="bg-white border border-stone-200 rounded-xl p-6 shadow-sm">
                            <h3 className="text-slate-900 font-bold mb-4">Live Preview</h3>
                            <div className="flex justify-center bg-stone-50 rounded-xl p-4 border border-stone-100">
                                <div className="w-48 shadow-2xl rounded-2xl overflow-hidden border-4 border-slate-900 bg-white">
                                    <BioPreview profile={currentProfile} links={availableLinks.filter(l => currentProfile.links?.includes(l.id))} />
                                </div>
                            </div>
                        </div>

                        <div className="bg-white border border-stone-200 rounded-xl p-6 flex flex-col shadow-sm h-[600px]">
                            <h3 className="text-slate-900 font-bold mb-4">Manage Links</h3>

                            <div className="flex-1 overflow-y-auto custom-scrollbar space-y-6 pr-2">
                                {/* Active Links Section */}
                                <div>
                                    <h4 className="text-xs font-bold text-stone-500 uppercase tracking-wider mb-3">
                                        Active Links ({activeLinksList.length})
                                    </h4>
                                    {activeLinksList.length === 0 ? (
                                        <div className="text-center py-8 bg-stone-50 rounded-xl border border-dashed border-stone-200">
                                            <p className="text-stone-400 text-sm">No links added yet.</p>
                                            <p className="text-stone-400 text-xs mt-1">Select links below to add them.</p>
                                        </div>
                                    ) : (
                                        <DndContext
                                            sensors={sensors}
                                            collisionDetection={closestCenter}
                                            onDragEnd={handleDragEnd}
                                        >
                                            <SortableContext
                                                items={activeLinksList.map(l => l.id)}
                                                strategy={verticalListSortingStrategy}
                                            >
                                                <div className="space-y-2">
                                                    {activeLinksList.map(link => (
                                                        <SortableBioLinkItem
                                                            key={link.id}
                                                            link={link}
                                                            onRemove={() => toggleLinkSelection(link.id)}
                                                        />
                                                    ))}
                                                </div>
                                            </SortableContext>
                                        </DndContext>
                                    )}
                                </div>

                                {/* Available Links Section */}
                                <div>
                                    <h4 className="text-xs font-bold text-stone-500 uppercase tracking-wider mb-3 pt-4 border-t border-stone-100">
                                        Available Links ({inactiveLinksList.length})
                                    </h4>
                                    <div className="space-y-2">
                                        {inactiveLinksList.length === 0 && <p className="text-stone-400 text-sm italic">No more links available.</p>}
                                        {inactiveLinksList.map(link => (
                                            <button
                                                key={link.id}
                                                onClick={() => toggleLinkSelection(link.id)}
                                                className="w-full flex items-center gap-3 p-3 rounded-lg border border-stone-200 hover:bg-stone-50 hover:border-yellow-400/50 transition-all group text-left"
                                            >
                                                <div className="w-8 h-8 rounded-lg bg-stone-100 flex items-center justify-center text-stone-400 group-hover:bg-yellow-100 group-hover:text-yellow-600 transition-colors">
                                                    <Plus className="w-4 h-4" />
                                                </div>
                                                <div className="overflow-hidden">
                                                    <p className="text-slate-900 text-sm font-medium truncate group-hover:text-yellow-700 transition-colors">{link.title}</p>
                                                    <p className="text-stone-500 text-xs truncate">{link.shortCode}</p>
                                                </div>
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="flex justify-end gap-3 mt-6">
                    <button onClick={() => setIsEditing(false)} className="px-6 py-2 text-stone-500 hover:text-slate-900">Cancel</button>
                    <button onClick={handleSave} className="px-6 py-2 bg-yellow-400 text-slate-900 rounded-xl font-bold hover:bg-yellow-500 shadow-sm shadow-yellow-400/20">Save Profile</button>
                </div>
            </div>
        );
    }

    if (loading) {
        return (
            <div className="min-h-screen bg-[#FDFBF7] flex items-center justify-center">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-yellow-400"></div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-[#FDFBF7]">
            <div className="p-8 max-w-7xl mx-auto">
                <div className="flex justify-between items-center mb-8">
                    <div>
                        <h1 className="text-2xl font-bold text-slate-900 mb-2">Link-in-Bio Profiles</h1>
                        <p className="text-stone-500">Manage your personal landing pages.</p>
                    </div>
                    <div className="flex gap-4">
                        <div className="relative">
                            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-stone-400" />
                            <input
                                type="text"
                                placeholder="Search profiles..."
                                value={searchQuery}
                                onChange={(e) => setSearchQuery(e.target.value)}
                                className="pl-10 pr-4 py-2 bg-white border border-stone-200 rounded-xl text-sm focus:ring-2 focus:ring-yellow-400 focus:border-transparent outline-none shadow-sm"
                            />
                        </div>
                        <button
                            onClick={handleCreateNew}
                            className="bg-yellow-400 hover:bg-yellow-500 text-slate-900 px-4 py-2 rounded-xl font-bold flex items-center gap-2 shadow-sm shadow-yellow-400/20"
                        >
                            <Plus className="w-5 h-5" /> Create Profile
                        </button>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {filteredProfiles.length === 0 ? (
                        <div className="col-span-3 text-center py-20 bg-white border border-stone-200 border-dashed rounded-2xl">
                            <UserCircle2 className="w-12 h-12 text-stone-300 mx-auto mb-4" />
                            <p className="text-stone-500 mb-4">
                                {searchQuery ? 'No profiles match your search.' : 'No profiles found.'}
                            </p>
                            <button onClick={handleCreateNew} className="text-yellow-600 font-bold hover:text-yellow-700">Create your first Link-in-Bio</button>
                        </div>
                    ) : (
                        filteredProfiles.map(profile => (
                            <div key={profile.id} className="bg-white border border-stone-200 rounded-2xl p-6 hover:border-yellow-400 transition-all group shadow-sm">
                                <div className="flex items-center gap-4 mb-6">
                                    <div className="w-12 h-12 rounded-full bg-stone-100 flex items-center justify-center overflow-hidden border border-stone-200">
                                        {profile.avatarUrl || user?.avatar_url ? (
                                            <img src={profile.avatarUrl || user?.avatar_url} alt="" className="w-full h-full object-cover" />
                                        ) : (
                                            <UserCircle2 className="w-8 h-8 text-stone-400" />
                                        )}
                                    </div>
                                    <div>
                                        <h3 className="text-slate-900 font-bold">{profile.displayName}</h3>
                                        <p className="text-stone-500 text-sm">@{profile.handle}</p>
                                    </div>
                                </div>

                                <div className="flex items-center justify-between mt-4 pt-4 border-t border-stone-100">
                                    <a
                                        href={`/p/${profile.handle}`}
                                        target="_blank"
                                        rel="noreferrer"
                                        className="text-yellow-600 text-sm font-bold flex items-center gap-1 hover:underline"
                                    >
                                        <ExternalLink className="w-3 h-3" /> Visit
                                    </a>
                                    <div className="flex gap-2">
                                        <button onClick={() => handleEdit(profile)} className="p-2 text-stone-400 hover:text-slate-900 hover:bg-stone-100 rounded-lg">
                                            <Edit className="w-4 h-4" />
                                        </button>
                                        <button onClick={() => handleDelete(profile.id)} className="p-2 text-stone-400 hover:text-red-500 hover:bg-red-50 rounded-lg">
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        ))
                    )}
                </div>
            </div>
        </div>
    );
};

export default BioDashboard;